### ISSUE TITLE
unilur does install in R 3.6.0

### ISSUE THREAD

**Issue by sampritban** [koncina/unilur#16]
Hi, I love unilur and have been using it for a while. Thank you for creating this package. However, I recently updated my RStudio and R and I am getting the following error for unilur installation. Can you please help?

R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> devtools::install_github("koncina/unilur")
Downloading GitHub repo koncina/unilur@master
cygwin warning:
  MS-DOS style path detected: C:\Users\sab2028\AppData\Local\Temp\RtmpWcjlJq\filed2864e0608b.tar.gz
  Preferred POSIX equivalent is: /cygdrive/c/Users/sab2028/AppData/Local/Temp/RtmpWcjlJq/filed2864e0608b.tar.gz
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
Error: Does not appear to be an R package (no DESCRIPTION)
>

**Comment by koncina** [comment]
I tried to install `unilur`on a windows VM and it seems to work in my hands. I don't think the issue is related to `unilur`.
Did you check which `tar` your Rstudio is using? (see the a similar [issue on devtools](https://github.com/r-lib/devtools/issues/1939) with a possible workaround using `Sys.setenv("TAR" = "internal")`).
I'm not actively using windows but as the `tar` binary is also shipped with Rtools, did you install it in the past? Did you update Rtools to the last version during your upgrade?

**Comment by sampritban** [comment]
Thanks so much for the response! It was an Rtools issue. Fixing the Rtools installation made it run correctly. Thanks again for your response and help!

Samprit.

**Comment by koncina** [comment]
I'm glad I could help and that you were able to solve your issue.
