### ISSUE TITLE
knitr CACHE prevent solution to be display in html output

### ISSUE THREAD

**Issue by ginolhac** [koncina/unilur#5]
If a global `knitr` CACHE option is to `TRUE` like this:

``` r setup, include=FALSE
knitr::opts_chunk$set(cache = TRUE)
```

no solution are displayed for the html output. Works fine with the pdf output.
Setting `knitr::opts_chunk$set(cache = FALSE)` solves the issue

**Comment by koncina** [comment]
Commit [3d43f9d](https://github.com/koncina/unilur/commit/3d43f9d88f20b831d29ccb0cfef6307e0bc045e0) contained a draft implementation of tutorial_html: A unique output file was rendered for both settings (solution `yes` and `no`).
Try a commit > [26080b0](https://github.com/koncina/unilur/commit/26080b080076b9be69c84ecc9ea1928a448a0971) to check if the problem is fixed (two different files are again generated depending on the `solution` setting).

**Caution:** Commit [26080b0](https://github.com/koncina/unilur/commit/26080b080076b9be69c84ecc9ea1928a448a0971) introduces the new developmental version (0.2) and `unilur::tutorial()` is now replaced by `tutorial_html()` and `tutorial_pdf()`. In addition `unilur::knit()` is removed (solution can be set to `yes` or `no`).

**Comment by ginolhac** [comment]
I guess this is on the `dev` branch. Also, version 0.2 is stated in the NEWS but not tagged.
Anyway, tested and got:

```
Error: 'tutorial_html' is not an exported object from 'namespace:unilur'
```

**Comment by koncina** [comment]
It is indeed still in the `dev` branch. Are you sure you didn't revert to the `master` branch which doesn't export `tutorial_html`?

**Comment by ginolhac** [comment]
working fine now
