### ISSUE TITLE
Custom Class and Header

### ISSUE THREAD

**Issue by mgoplerud** [koncina/unilur#9]
Hello!

I was wondering if it was possible to make two slight modifications to the package.

1) To allow a user to specify the custom document class. As it stands now, this would accept a custom class, but I can't see how to manually specify it from RStudio's Rmarkdown directly.

tutorial_pdf_base <- function(solution = FALSE,          
                              solution_suffix = "_solution",
                              question_suffix = "_question",
                              credit = FALSE,                 # Show a link to the unilur homepage
                              latex_class = "article",
                              pandoc_args = NULL, ...

2) Similarly, is it possible to specify the path to a custom header? (I.e. given a different filepath to header_examen)

    header_examen <- system.file("rmarkdown", "templates", "tutorial", "resources", "header_examen.tex",
                                 package = "unilur")

**Comment by koncina** [comment]
Hello,

1) When using `tutorial_pdf` / `tutorial_pdf_solution` you can already adjust the `latex_class` argument in the yaml header. For example, the following header would use the report class instead of the article class:

```
---
title: 'Title'
author: 'John Doe'
date: '16/01/18'
output:
  unilur::tutorial_pdf:
    latex_class: "report"
  unilur::tutorial_pdf_solution:
    latex_class: "report"
---
```
However, this is not possible for the `unilur::examen_pdf` format as it already overrides the class (in order to use the exam class).

This option will be passed to pandoc as the `documentclass` variable (see [here](https://pandoc.org/MANUAL.html#variables-for-latex)). It can be adjusted to a `.cls` file path  (omit the `.cls` extension as it will be added by pandoc).

Pandoc itself will use it to set the class within the template (using `\documentclass{...}`) . Thus it might (or even will likely) fail if the class you're using defines options collapsing with some settings used in the current template (pandoc and/or unilur customisation).

2) It is also possible to define custom headers (using the includes argument). I changed the inclusion priority in the [latest commit](https://github.com/koncina/unilur/commit/c7c2f0bcb5db4112d366b7ee5333577b94bbeac8) allowing you to override the current header defined in `header_examen.tex`.

For example, create your own `my_header.tex` (in the same folder as your `.Rmd` file):
```
\pagestyle{headandfoot}
\firstpagefooter{Left footer}{Center footer}{Right footer}
\runningfooter{Left footer}{Center footer}{Right footer}
\firstpageheader{Left header}{Center header}{Right header}
\runningheader{Left header}{Center header}{Right header}
```

and in your Rmarkdown document include the file using:

```
---
title: 'Title'
author: 'John Doe'
date: '16/01/18'
output:
  unilur::examen_pdf:
    includes:
      in_header: my_header.tex
---
```

By default the defined footer/header will only appear starting from page 2. To use your custom header already on the first page, start your document (just after the yaml header) with the latex command:

`\thispagestyle{headandfoot}`

I hope that helps.

Eric

**Comment by koncina** [comment]
The `latex_class` argument was removed in a recent commit. Though you can still change the document class using the "official rmarkdown" syntax and the top-level `documentclass` yaml metadata variable ([see here](https://bookdown.org/yihui/rmarkdown/pdf-document.html#latex-options)).
